version: "3.9"

services:
  telegram-bot:
    build:
      context: .
      args:
        APP_PATH: ${APP_PATH}
    container_name: croak-nb-telegram-bot
    environment:
      PYTHONPATH: ${APP_PATH}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_LOGIC_DATABASE: ${REDIS_LOGIC_DATABASE}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    restart: no
    volumes:
      - ./src:${APP_PATH}/src
      - ./dynamic:${APP_PATH}/dynamic
      - ./.env.python:${APP_PATH}/.env.python
    networks:
        - croak-nb-network
  database:
    image: postgres:18
    container_name: danny-glass-database
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    restart: no
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - croak-nb-network
    ports:
      - "5432:5432"
  redis:
    image: redis:7-alpine
    container_name: danny-glass-redis
    command: sh -c "redis-server --requirepass ${REDIS_PASSWORD}"
    volumes:
      - redis_data:/data
    restart: no
    networks:
      - croak-nb-network

networks:
  croak-nb-network:
    driver: bridge
volumes:
  redis_data:
  postgres_data: