main:
  cancel_button: "Отмена ↩"
start_menu:
  caption: |
    Привет, <u>{0}</u>.
    
    CroakNB - это лучший способ использования интернета
  status_menu_button: "Статус"
  support_menu_button: "Поддержка"
  connect_menu_button:          "Подключиться"
  inactive_connect_menu_button: "Подключиться"

status_menu:
  caption_without_active_product: |
    Ваша подписка CroakNB не оплачена.
    - Стоимость подписки: {0}₽.
    
    Оплатив подписку в первый раз вы получите продукт в течение дня.
  caption_with_active_product: |
    - Ваша подписка CroakNB активна до {1}.
    - Стоимость подписки: {0}₽.

connect_menu:
  caption: |
    Ваша индивидуальная подписка в формате <b>Happ</b>:
    
    <pre>{0}</pre>
  inactive_answer_message: "Ваша подписка закончилась."