main:
  cancel_button: "Отмена"

start_menu:
  caption: |
    Привет, <u>{0}</u>.
    
    <b>CroakNB</b> - имперское платное программное обеспечение, обеспечивающее лучшое интернет соединение на планете.
    
    Наш продукт <u>обеспечивает</u> хорошое быстрое и безопасное соединение, а также активную поддержку.
  status_menu_button: "Статус"
  prolong_menu_button: "Продлить"
  offer_menu_button: "Оферта"
  support_menu_button: "Поддержка"
  connect_menu_button:          "Подключиться"
  inactive_connect_menu_button: "Подключиться"
  admin_menu_button: "Админ панель"

admin_menu:
  caption: |
    Здравствуйте великий повелитель бота!

prolong_menu:
  caption: |
    Перед оплатой убедитесь, что вы прочитали <u>оферту</u> продукта и полностью с ней согласны. Оплачивая товар, вы подтверждаете, что ознакомлены с условиями оферты.
    
    Оплата происходит средством прямого перевода через СБП на банковский счет т банк'а.
  copy_bank_address_button: "Скопировать номер"

status_menu:
  caption_without_active_product: |
    Ваша подписка <u>истекла</u>.
    Текущая стоимость подписки: <b>{0}₽ / 29 дн</b>.
    
    Продлите подписку что-бы продолжать использование CroakNB!
  caption_with_active_product: |
    Ваша подписка <u>активна</u> до {1}.
    Текущая стоимость подписки: <b>{0}₽ / 29 дн</b>.

    Не забудьте оплатить подписку!

main_connect_menu:
  caption: |
    ㅤ
    Добавте конфигурацию ниже в <b>Happ</b>:
    
    <pre>{0}</pre>
    индивидуальная подписка | main | happ

wl_connect_menu:
  caption: |
    ㅤ
    Добавте конфигурацию ниже в <b>Happ</b>:

    <pre>{0}</pre>
    глобальная подписка | wl | happ

connect_menu:
  caption: |
    Сервис <b>CroakNB</b> предоставляет несколько вариантов подключения.
    
    Скачать Happ:
      - <a href="{0}"><u>Happ под Windows</u></a>
      - <a href="{1}"><u>Happ под Linux</u></a>
      - <a href="{2}"><u>Happ под Android</u></a>
    
    Выберите подключение ниже:
  main_connect_menu_button: "HAPP | Основное подключение"
  wl_connect_menu_button: "HAPP | Белые списки"

  inactive_answer_message: "Ваша подписка закончилась."

offer_menu:
  caption: |   
    Настоящая оферта может быть изменена Администрацией в любое время без каких-либо ограничений по дате и времени, без предварительного уведомления пользователей.
    
    Текст оферты размещается в отдельном документе в связи с техническими ограничениями платформы Telegram.
  read_button: "Читать"
