main:
  cancel_button: "Отмена"

start_menu:
  caption: |
    Привет, <u>{0}</u>.
    
    <b>CroakNB</b> - имперское платное программное обеспечение, обеспечивающее лучшое интернет соединение на планете.
    
    Наш продукт <u>обеспечивает</u> хорошое быстрое и безопасное соединение, а также активную поддержку.
    
    Узнать больше о CroakNB можно в <u>Оферте</u> продукта и в <u>Статусе</u>.
  status_menu_button: "Статус"
  offer_menu_button: "Оферта"
  support_menu_button: "Поддержка"
  connect_menu_button:          "Подключиться"
  inactive_connect_menu_button: "Подключиться"
  admin_menu_button: "Админ панель"

admin_menu:
  caption: |
    Здравствуйте великий повелитель бота!

status_menu:
  caption_without_active_product: |
    Ваша подписка <u>истекла</u>.
    
    Продлите подписку что-бы продолжать использование CroakNB!
    
    - Стоимость подписки: <b>{0}₽ / 29 дн</u>.
  caption_with_active_product: |
    Ваша подписка <u>активна</u> до {1}.
    
    Не забудьте оплатить подписку!
    
    - Стоимость подписки: <b>{0}₽ / 29 дн</b>.

connect_menu:
  caption: |
    ㅤ
    - <a href="{1}"><u>Happ под Windows</u></a>
    - <a href="{2}"><u>Happ под Linux</u></a>
    - <a href="{3}"><u>Happ под Android</u></a>
    
    Добавте конфигурацию ниже в <b>Happ</b>:
    
    <pre>{0}</pre>
  inactive_answer_message: "Ваша подписка закончилась."

offer_menu:
  caption: |   
    Настоящая оферта может быть изменена Администрацией в любое время без каких-либо ограничений по дате и времени, без предварительного уведомления пользователей.
    
    Текст оферты размещается в отдельном документе в связи с техническими ограничениями платформы Telegram.
  read_button: "Читать"
