telegram_image_cache:
  telegram_user_id: 1087240511
  expire_minutes: 60.0
product:
  default_cost: 200
support:
  url: "https://t.me/mrfufl4ik"
offer:
  url: "https://docs.google.com/document/d/1RRzR9hVJme4wxMta9XE_vQbU2174cvW-YYoBiT3bTRw/edit?usp=sharing"