telegram_image_cache:
  telegram_user_id: 1087240511
  expire_minutes: 60.0
product:
  default_cost: 200
  subscription_day_count: 29
prolong:
  bank_address: "+09161234567"
support:
  url: "https://t.me/mrfufl4ik"
offer:
  url: "https://nb.croakland.ru/offer"
connect:
  download_link_windows:  "https://nb.croakland.ru/download/happ/windows"
  download_link_linux:    "https://nb.croakland.ru/download/happ/linux"
  download_link_android:  "https://nb.croakland.ru/download/happ/android"